apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Release.Name } }
  labels:
    app: chocolatelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chocolatelab
  template:
    metadata:
      labels:
        app: chocolatelab
    spec:
      containers:
        - name: chocolatelab
          image: chocolatelab:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: '3002'
            - name: CHOCOLATE_LAB_STORAGE_TYPE
              value: 'mongo'
            - name: MONGODB_HOST
              value: '{{ .Values.mongodb.host }}'
            - name: MONGODB_PORT
              value: '{{ .Values.mongodb.port }}'
            - name: MONGODB_USER
              value: '{{ .Values.mongodb.username }}'
            - name: MONGODB_PASSWORD
              value: '{{ .Values.mongodb.password }}'
            - name: MONGODB_DATABASE
              value: '{{ .Values.mongodb.databases.chocolatelab }}'
            - name: STATIC_FILES_PATH
              value: './static'
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: '2'
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
