// Copyright (c) 2026 Erik Fortune
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

export const Cities: ReadonlyArray<string> = [
  'Abidjan',
  'Abu Dhabi',
  'Accra',
  'Addis Ababa',
  'Ahmedabad',
  'Alexandria',
  'Algiers',
  'Almaty',
  'Amman',
  'Amsterdam',
  'Ankara',
  'Antwerp',
  'Asunción',
  'Athens',
  'Atlanta',
  'Auckland',
  'Baghdad',
  'Baku',
  'Bangkok',
  'Bangalore',
  'Barcelona',
  'Beirut',
  'Belgrade',
  'Belo Horizonte',
  'Berlin',
  'Bilbao',
  'Birmingham',
  'Bogotá',
  'Bordeaux',
  'Boston',
  'Bratislava',
  'Brisbane',
  'Brussels',
  'Bucharest',
  'Budapest',
  'Buenos Aires',
  'Busan',
  'Cairo',
  'Cape Town',
  'Caracas',
  'Casablanca',
  'Chengdu',
  'Chennai',
  'Chicago',
  'Chongqing',
  'Cologne',
  'Colombo',
  'Copenhagen',
  'Dakar',
  'Dalian',
  'Dallas',
  'Damascus',
  'Dar es Salaam',
  'Delhi',
  'Denver',
  'Detroit',
  'Dhaka',
  'Doha',
  'Dubai',
  'Dublin',
  'Durban',
  'Edinburgh',
  'Florence',
  'Foshan',
  'Frankfurt',
  'Fukuoka',
  'Geneva',
  'Glasgow',
  'Guadalajara',
  'Guatemala City',
  'Hamburg',
  'Hangzhou',
  'Hanoi',
  'Harare',
  'Harbin',
  'Havana',
  'Helsinki',
  'Ho Chi Minh City',
  'Hong Kong',
  'Houston',
  'Hyderabad',
  'Incheon',
  'Islamabad',
  'Istanbul',
  'Izmir',
  'Jakarta',
  'Jerusalem',
  'Jinan',
  'Johannesburg',
  'Kabul',
  'Kampala',
  'Karachi',
  'Kathmandu',
  'Khartoum',
  'Kinshasa',
  'Kolkata',
  'Krakow',
  'Kuala Lumpur',
  'Kuwait City',
  'Kyiv',
  'La Paz',
  'Lagos',
  'Lahore',
  'Leeds',
  'Lima',
  'Lisbon',
  'Liverpool',
  'Ljubljana',
  'London',
  'Los Angeles',
  'Luanda',
  'Lusaka',
  'Lyon',
  'Madrid',
  'Managua',
  'Manchester',
  'Manila',
  'Maputo',
  'Marseille',
  'Medellín',
  'Melbourne',
  'Mexico City',
  'Miami',
  'Milan',
  'Minneapolis',
  'Minsk',
  'Montevideo',
  'Moscow',
  'Mumbai',
  'Munich',
  'Muscat',
  'Nagoya',
  'Nairobi',
  'Nanjing',
  'Naples',
  'New York',
  'Nice',
  'Osaka',
  'Oslo',
  'Panama City',
  'Paris',
  'Perth',
  'Philadelphia',
  'Phnom Penh',
  'Phoenix',
  'Porto',
  'Prague',
  'Pune',
  'Pyongyang',
  'Qingdao',
  'Quito',
  'Rabat',
  'Regensburg',
  'Riga',
  'Rio de Janeiro',
  'Riyadh',
  'Rome',
  'Rotterdam',
  'Saint Petersburg',
  'San Diego',
  'San Francisco',
  'San José',
  'San Juan',
  'Santiago',
  'Santo Domingo',
  'São Paulo',
  'Seattle',
  'Seoul',
  'Seville',
  'Shanghai',
  'Shenyang',
  'Shenzhen',
  'Singapore',
  'Sofia',
  'Stockholm',
  'Stuttgart',
  'Surat',
  'Suzhou',
  'Sydney',
  'Taipei',
  'Tallinn',
  'Tashkent',
  'Tbilisi',
  'Tegucigalpa',
  'Tehran',
  'Tel Aviv',
  'Tianjin',
  'Tokyo',
  'Toronto',
  'Toulouse',
  'Tripoli',
  'Tunis',
  'Turin',
  'Ulaanbaatar',
  'Valencia',
  'Venice',
  'Vienna',
  'Vientiane',
  'Vilnius',
  'Warsaw',
  'Washington',
  'Wellington',
  'Wuhan',
  'Yangon',
  'Yerevan',
  'Zagreb',
  'Zurich'
];
