// Copyright (c) 2026 Erik Fortune
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

export const Gerunds: ReadonlyArray<string> = [
  'running',
  'jumping',
  'swimming',
  'walking',
  'talking',
  'singing',
  'dancing',
  'reading',
  'writing',
  'thinking',
  'sleeping',
  'eating',
  'drinking',
  'working',
  'playing',
  'studying',
  'learning',
  'teaching',
  'cooking',
  'cleaning',
  'driving',
  'flying',
  'climbing',
  'falling',
  'growing',
  'building',
  'creating',
  'designing',
  'painting',
  'drawing',
  'listening',
  'watching',
  'waiting',
  'hoping',
  'dreaming',
  'planning',
  'organizing',
  'managing',
  'leading',
  'following',
  'helping',
  'supporting',
  'caring',
  'loving',
  'hating',
  'feeling',
  'understanding',
  'knowing',
  'believing',
  'trusting',
  'fighting',
  'winning',
  'losing',
  'trying',
  'failing',
  'succeeding',
  'improving',
  'changing',
  'moving',
  'staying',
  'leaving',
  'arriving',
  'beginning',
  'ending',
  'starting',
  'finishing',
  'opening',
  'closing',
  'breaking',
  'fixing',
  'making',
  'taking',
  'giving',
  'receiving',
  'sending',
  'buying',
  'selling',
  'trading',
  'sharing',
  'hiding',
  'seeking',
  'finding',
  'losing',
  'searching',
  'exploring',
  'discovering',
  'inventing',
  'solving',
  'questioning',
  'answering',
  'asking',
  'telling',
  'showing',
  'proving',
  'testing',
  'measuring',
  'counting',
  'calculating',
  'programming',
  'coding',
  'debugging',
  'deploying',
  'launching',
  'shipping'
];
