// Copyright (c) 2026 Erik Fortune
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

export const jobs: string[] = [
  'Accountant',
  'Actor',
  'Actuary',
  'Administrator',
  'Advertising Manager',
  'Aerospace Engineer',
  'Agricultural Scientist',
  'Air Traffic Controller',
  'Animator',
  'Anthropologist',
  'Archaeologist',
  'Architect',
  'Art Director',
  'Astronomer',
  'Attorney',
  'Audiologist',
  'Baker',
  'Banker',
  'Barber',
  'Biologist',
  'Biomedical Engineer',
  'Bookkeeper',
  'Broadcast Technician',
  'Bus Driver',
  'Business Analyst',
  'Carpenter',
  'Cartographer',
  'Chef',
  'Chemical Engineer',
  'Chemist',
  'Chiropractor',
  'Civil Engineer',
  'Clinical Psychologist',
  'Coach',
  'Computer Programmer',
  'Construction Manager',
  'Consultant',
  'Content Writer',
  'Copywriter',
  'Counselor',
  'Court Reporter',
  'Curator',
  'Data Analyst',
  'Data Scientist',
  'Database Administrator',
  'Dental Hygienist',
  'Dentist',
  'Dermatologist',
  'Dietitian',
  'Director',
  'Economist',
  'Editor',
  'Electrical Engineer',
  'Electrician',
  'Elementary School Teacher',
  'Emergency Medical Technician',
  'Engineer',
  'Environmental Scientist',
  'Epidemiologist',
  'Event Planner',
  'Fashion Designer',
  'Film Director',
  'Financial Advisor',
  'Financial Analyst',
  'Firefighter',
  'Fitness Trainer',
  'Flight Attendant',
  'Florist',
  'Forensic Scientist',
  'Fundraiser',
  'Geologist',
  'Graphic Designer',
  'Hairdresser',
  'Health Educator',
  'Historian',
  'Human Resources Manager',
  'Industrial Designer',
  'Industrial Engineer',
  'Insurance Agent',
  'Interior Designer',
  'Interpreter',
  'Investment Banker',
  'IT Manager',
  'Journalist',
  'Judge',
  'Landscape Architect',
  'Lawyer',
  'Librarian',
  'Loan Officer',
  'Logistician',
  'Machine Operator',
  'Makeup Artist',
  'Management Consultant',
  'Manufacturing Engineer',
  'Marine Biologist',
  'Market Research Analyst',
  'Marketing Manager',
  'Massage Therapist',
  'Mathematician',
  'Mechanical Engineer',
  'Medical Assistant',
  'Microbiologist',
  'Musician',
  'Network Administrator',
  'Neurologist',
  'Nuclear Engineer',
  'Nurse',
  'Nutritionist',
  'Occupational Therapist',
  'Optometrist',
  'Paralegal',
  'Paramedic',
  'Park Ranger',
  'Pediatrician',
  'Pharmacist',
  'Photographer',
  'Physical Therapist',
  'Physician',
  'Physicist',
  'Pilot',
  'Plumber',
  'Police Officer',
  'Political Scientist',
  'Producer',
  'Product Manager',
  'Professor',
  'Project Manager',
  'Psychiatrist',
  'Psychologist',
  'Public Relations Specialist',
  'Quality Assurance Analyst',
  'Radiologist',
  'Real Estate Agent',
  'Receptionist',
  'Registered Nurse',
  'Reporter',
  'Research Scientist',
  'Respiratory Therapist',
  'Sales Manager',
  'Social Worker',
  'Software Developer',
  'Software Engineer',
  'Statistician',
  'Surgeon',
  'Surveyor',
  'Systems Analyst',
  'Teacher',
  'Technical Writer',
  'Urban Planner',
  'Veterinarian',
  'Web Developer',
  'Writer',
  'Zoologist'
] as const;
