/**
 * Manually-invoked data pipeline (chocolate-lab pattern). Walks `samples/testbed/data/`,
 * collects YAML/JSON files into an in-memory file-tree spec, and writes the result to
 * `src/generated/dataFileTree.ts` — which IS checked in (so consumers don't need to run
 * the pipeline to build).
 *
 * Run via:
 *   rushx build:data
 *
 * At B-1 the `data/` directory is empty, so the script emits an empty tree. Scenarios
 * that need source data drop files under `data/` and re-run the script.
 *
 * Binary data is intentionally excluded — scenarios that need binary assets fetch at
 * runtime or skip.
 *
 * @packageDocumentation
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const TEXT_EXTENSIONS = new Set(['.yaml', '.yml', '.json', '.md', '.txt']);

interface IFileEntry {
  readonly path: string;
  readonly payload: string;
}

function walk(dir: string, baseDir: string, out: IFileEntry[]): void {
  if (!fs.existsSync(dir)) {
    return;
  }
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, baseDir, out);
    } else if (entry.isFile() && TEXT_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
      const rel = path.relative(baseDir, full).split(path.sep).join('/');
      const payload = fs.readFileSync(full, 'utf8');
      out.push({ path: rel, payload });
    }
  }
}

function render(entries: IFileEntry[]): string {
  const header =
    '/**\n' +
    ' * AUTO-GENERATED by samples/testbed/scripts/build-data.ts — DO NOT EDIT BY HAND.\n' +
    ' * Re-run `rushx build:data` after touching samples/testbed/data/.\n' +
    ' */\n\n';

  const serialized = entries
    .map((e) => `  { path: ${JSON.stringify(e.path)}, payload: ${JSON.stringify(e.payload)} }`)
    .join(',\n');

  return (
    header +
    "import type { FileTree } from '@fgv/ts-json-base';\n\n" +
    '/**\n' +
    ' * Raw in-memory file specs assembled from samples/testbed/data/. Empty at B-1.\n' +
    ' * Pass to `FileTree.inMemory(dataFiles)` in a scenario to mount as a FileTree.\n' +
    ' * @public\n' +
    ' */\n' +
    'export const dataFiles: ReadonlyArray<FileTree.IInMemoryFile> = [\n' +
    serialized +
    (serialized.length > 0 ? '\n' : '') +
    '];\n'
  );
}

function main(): void {
  const root = path.resolve(__dirname, '..');
  const dataDir = path.join(root, 'data');
  const outFile = path.join(root, 'src', 'generated', 'dataFileTree.ts');

  const entries: IFileEntry[] = [];
  walk(dataDir, dataDir, entries);
  entries.sort((a, b) => a.path.localeCompare(b.path));

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, render(entries), 'utf8');

  process.stdout.write(
    `build-data: wrote ${entries.length} entr${entries.length === 1 ? 'y' : 'ies'} to ${path.relative(
      root,
      outFile
    )}\n`
  );
}

main();
